In [1]:
import pandas as pd

In [2]:
df  = pd.read_csv('../data/desempeño_areas_formacion.csv')

In [3]:
df.head()

,PERIODO,FACULTAD,UNIDAD,PENSUM,DOCUMENTO,NOMBRES,MATRICULA_ACTUAL,SITUACION_ACTUAL,CATEGORIA_ACTUAL,CIENCIAS BÁSICAS,CIENCIAS BÁSICAS DE INGENIERÍA,INGENIERÍA APLICADA,INSTITUCIONAL,TOTAL_BAJO_RENDIMIENTO_REA,DESERTA
0,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1000136072,FORERO HERRERA TANIA NICKOLL,SIN MATRICULA,ACTIVO,CONTINUIDAD ACADEMICA - EGRESADO,3.553846,3.956154,3.951915,3.897200,2,0
1,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1000320087,MESA BLANCO LEONARDO JUAN,SIN MATRICULA,ACTIVO,ANTIGUO,3.310833,3.297368,3.661538,3.761000,9,0
2,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1000592838,BAUTISTA DIAZ DANIEL EDUARDO,SIN MATRICULA,ACTIVO,CONTINUIDAD ACADEMICA - EGRESADO,3.475000,3.625714,3.960278,3.890833,6,0
3,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1001346777,SUAREZ HEREDIA JUAN SEBASTIAN,SIN MATRICULA,EXCLUIDO BAJO RENDIMIENTO,ANTIGUO,3.171429,2.900000,3.100000,3.000000,7,1
4,2019-1,FACULTAD DE INGENIERÍA,"UNIDAD REGIONAL, SEDE FUSAGASUGÁ",INGENIERIA DE SISTEMAS Y COMPUTACION 2020 FUSA...,1003515700,ESCOBAR VASQUEZ JENIFFER DAYANA,SIN MATRICULA,EXCLUIDO BAJO RENDIMIENTO,ANTIGUO,3.328571,2.623529,3.900000,3.485714,10,1

In [4]:
df_2 = pd.read_csv("udec_desercion_isc_caracterizacion.csv")

In [5]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 0)     # autodetecta ancho
display(df_2.head(20))

,DOCUMENTO,GENERO,UBICACION_SEMESTRAL,MEDIO_TRANSPORTE,FRECUENCIA_TRANSPORTE,FUENTES_FINANCIACION,PERSONAS_A_CARGO,DIFICULTAD_PAGO_MATRICULA,TURNO_TRABAJO_ESTUDIO,TIPO_VIVIENDA_RESIDENCIA,ZONA_VIVIENDA_RESIDENCIA,VIVE_PADRES_FAMILIAR,SISBEN,NUM_HIJOS,VIVE_PERSONAS_MAYORES,VIVE_PERSONAS_PATOLOGIAS,VICTIMA_VIOLENCIA,FRECUENCIA_USO_CANALES_ATENCION,ORIENTACION_CAT,COMUNA,NIV_EDUCATIVO_PADRE_CAT,NIV_EDUCATIVO_MADRE_CAT,ES_VULNERABLE,ES_GRUPO_ETNICO,GRUPO_ETNICO_CAT,HORAS_FUERA_CASA,RECURSOS_TECNOLOGICOS,HERMANOS_CAT,CARGA_LABORAL,CARGA_HOGAR,CONDICION_DISCAPACIDAD,HABITOS_RIESGO,IMC_CAT
0,1069737604,M,2,Bicicleta,Otro,Recursos propios,CON_CARGAS,Si,Mixto,Propia pagada,Zona urbana,Si,No,2,Si,No,No,Con poca frecuencia,Heterosexual,Comuna Sur Occidental,Media,Media,No,No,No étnico,MEDIO,COMPLETOS,POCOS_1_2,NO_TRABAJA,CON_NINOS_1_2,COGNITIVA,NINGUNO,OBESIDAD
1,1026290752,M,9,Vehículo motorizado,Baja frecuencia,Recursos propios,CON_CARGAS,Si,Mixto,Propia pagada,Zona urbana,Si,No,1,No,No,No,Casi nunca,Heterosexual,Bogota,Media,Media,No,No,No étnico,BAJO,COMPLETOS,VARIOS_3_MAS,NO_TRABAJA,CON_NINOS_1_2,COGNITIVA,BAJO,SOBREPESO
2,1069750774,M,9,A pie,Baja frecuencia,Recursos propios,CON_CARGAS,Si,Diurno,Arrendada,Zona urbana,Si,No,1,Si,No,NaN,Casi nunca,No responde,Comuna Sur Occidental,Media,Media,No,No,No étnico,ALTO,COMPLETOS,VARIOS_3_MAS,NO_TRABAJA,HOGAR_SIN_NINOS,COGNITIVA,NINGUNO,SOBREPESO
3,1069747785,M,5,A pie,Alta frecuencia,Otro / No aplica,SIN_CARGAS,Si,Diurno,Arrendada,Zona urbana,Si,Si,0,No,No,No,Con poca frecuencia,No responde,Comuna Occidental,Superior,Superior,No,No,No étnico,ALTO,COMPLETOS,POCOS_1_2,ALTA_>20,HOGAR_SIN_NINOS,COGNITIVA,BAJO,SOBREPESO
4,1069760977,M,9,A pie,Baja frecuencia,Recursos propios,SIN_CARGAS,Si,Mixto,Arrendada,Zona urbana,Si,No,0,Si,No,Si,Casi nunca,Heterosexual,Comuna Sur Oriental,Básica,Básica,No,No,No étnico,ALTO,BASICOS,VARIOS_3_MAS,ALTA_>20,CON_NINOS_3_MAS,COGNITIVA,BAJO,NORMAL
5,1069744582,M,8,Servicio público,Baja frecuencia,Recursos propios,SIN_CARGAS,No,Diurno,Arrendada,Zona rural,Si,No,0,No,No,No,Casi nunca,No responde,Comuna Centro,Media,Básica,No,No,No étnico,BAJO,COMPLETOS,POCOS_1_2,PARCIAL_1_20,HOGAR_SIN_NINOS,COGNITIVA,NINGUNO,SOBREPESO
6,1069755791,M,3,Servicio público,Baja frecuencia,Recursos propios,SIN_CARGAS,Si,Diurno,Propia pagada,Zona urbana,Si,Si,0,Si,No,No,Frecuentemente,Heterosexual,Comuna Sur Occidental,Media,Media,No,No,No étnico,BAJO,COMPLETOS,NINGUNO,NO_TRABAJA,HOGAR_SIN_NINOS,COGNITIVA,NINGUNO,SOBREPESO
7,1032460863,M,8,Bicicleta,Baja frecuencia,Recursos propios,SIN_CARGAS,No,Diurno,Arrendada,Zona urbana,Si,No,0,No,No,NaN,Casi nunca,No responde,Bogota,Media,Superior,No,No,No étnico,MEDIO,COMPLETOS,POCOS_1_2,PARCIAL_1_20,SOLO_SIN_NINOS,COGNITIVA,NINGUNO,NORMAL
8,1069749942,M,0,Servicio público,Baja frecuencia,Recursos propios,CON_CARGAS,No,Mixto,Arrendada,Zona urbana,Si,Si,1,Si,No,No,Casi nunca,Heterosexual,Comuna Norte,Básica,Básica,No,No,No étnico,MEDIO,BASICOS,NINGUNO,ALTA_>20,CON_NINOS_1_2,SIN,NINGUNO,SOBREPESO
9,1015451974,M,9,Servicio público,Baja frecuencia,Recursos propios,SIN_CARGAS,Si,Diurno,Propia pagada,Zona urbana,Si,Si,0,Si,No,No,Casi nunca,No responde,Comuna Centro,Básica,Media,No,No,No étnico,MEDIO,BASICOS,POCOS_1_2,NO_TRABAJA,HOGAR_SIN_NINOS,MULTIPLE,BAJO,OBESIDAD
10,1069758182,M,9,A pie,Baja frecuencia,Recursos propios,SIN_CARGAS,No,Diurno,Arrendada,Zona urbana,No,No,0,No,No,NaN,Frecuentemente,No responde,Comuna Occidental,Superior,Superior,No,No,No reportado,MEDIO,COMPLETOS,VARIOS_3_MAS,NO_TRABAJA,SOLO_SIN_NINOS,MULTIPLE,BAJO,NORMAL
11,1030622115,M,9,A pie,Baja frecuencia,Recursos propios,CON_CARGAS,Si,Diurno,Arrendada,Zona urbana,Si,Si,1,Si,No,No,Con poca frecuencia,No responde,Comuna Norte,Media,Media,No,No,No étnico,BAJO,BASICOS,POCOS_1_2,NO_TRABAJA,CON_NINOS_1_2,COGNITIVA,NINGUNO,SOBREPESO
12,1069762616,M,9,A pie,Otro,Recursos propios,CON_CARGAS,Si,Mixto,Propia pagada,Zona urbana,Si,No,0,Si,No,No,Frecuentemente,Heterosexual,Comuna Occidental,Superior,Media,No,No,No étnico,ALTO,COMPLETOS,POCOS_1_2,NO_TRABAJA,CON_NINOS_1_2,COGNITIVA,NINGUNO,BAJO_PESO
13,1069762376,M,9,A pie,Baja frecuencia,Recursos propios,SIN_CARGAS,Si,Diurno,Propia pagada,Zona urbana,Si,No,0,No,No,No,Nunca,No responde,Comuna Norte,Básica,Media,No,No,No étnico,ALTO,COMPLETOS,POCOS_1_2,NO_TRABAJA,HOGAR_SIN_NINOS,COGNITIVA,BAJO,NORMAL
14,1069760378,M,5,Servicio público,Baja frecuencia,Otro / No aplica,SIN_CARGAS,No,Diurno,Propia pagandose,Zona urbana,Si,No,0,No,No,No,Casi nunca,No responde,Comuna Norte,Media,Media,No,No,No étnico,ALTO,COMPLETOS,POCOS_1_2,PARCIAL_1_20,SOLO_SIN_NINOS,COGNITIVA,NINGUNO,SOBREPESO
15,1022418555,M,9,Servicio público,Baja frecuencia,Recursos propios,CON_CARGAS,Si,Diurno,Arrendada,Zona urbana,Si,Si,0,Si,No,No,Casi nunca,No responde,Bogota,Media,Media,No,No,No étnico,BAJO,COMPLETOS,NINGUNO,NO_TRABAJA,SOLO_SIN_NINOS,COGNITIVA,BAJO,NORMAL
16,1069743740,F,9,Servicio público,Baja frecuencia,Recursos propios,CON_CARGAS,Si,Diurno,Arrendada,Zona rural,Si,Si,0,No,No,No,Frecuentemente,No responde,Municipios Aledaños,Media,Media,No,No,No étnico,ALTO,BASICOS,NINGUNO,NO_TRABAJA,HOGAR_SIN_NINOS,COGNITIVA,BAJO,BAJO_PESO
17,1069761647,M,9,A pie,Alta frecuencia,Recursos propios,CON_CARGAS,Si,Diurno,Arrendada,Zona urbana,No,Si,0,No,No,No,Casi nunca,No responde,Comuna Centro,Media,Superior,No,No,No étnico,ALTO,BASICOS,VARIOS_3_MAS,NO_TRABAJA,CON_NINOS_1_2,COGNITIVA,NINGUNO,SOBREPESO
18,1069761810,M,8,Vehículo motorizado,Baja frecuencia,Beca,CON_CARGAS,Si,Diurno,Arrendada,Zona rural,Si,Si,1,No,No,NaN,Con poca frecuencia,No responde,Municipios Aledaños,Básica,Básica,No,No,No étnico,MEDIO,BASICOS,VARIOS_3_MAS,PARCIAL_1_20,CON_NINOS_3_MAS,COGNITIVA,NINGUNO,NORMAL
19,1106900081,F,9,Servicio público,Baja frecuencia,Recursos propios,SIN_CARGAS,Si,Diurno,Arrendada,Zona urbana,Si,Si,0,No,No,No,Con poca frecuencia,No responde,Municipios Aledaños,Media,Media,No,No,No étnico,BAJO,COMPLETOS,VARIOS_3_MAS,NO_TRABAJA,HOGAR_SIN_NINOS,COGNITIVA,BAJO,SOBREPESO

In [6]:
df_2

,DOCUMENTO,GENERO,UBICACION_SEMESTRAL,MEDIO_TRANSPORTE,FRECUENCIA_TRANSPORTE,FUENTES_FINANCIACION,PERSONAS_A_CARGO,DIFICULTAD_PAGO_MATRICULA,TURNO_TRABAJO_ESTUDIO,TIPO_VIVIENDA_RESIDENCIA,ZONA_VIVIENDA_RESIDENCIA,VIVE_PADRES_FAMILIAR,SISBEN,NUM_HIJOS,VIVE_PERSONAS_MAYORES,VIVE_PERSONAS_PATOLOGIAS,VICTIMA_VIOLENCIA,FRECUENCIA_USO_CANALES_ATENCION,ORIENTACION_CAT,COMUNA,NIV_EDUCATIVO_PADRE_CAT,NIV_EDUCATIVO_MADRE_CAT,ES_VULNERABLE,ES_GRUPO_ETNICO,GRUPO_ETNICO_CAT,HORAS_FUERA_CASA,RECURSOS_TECNOLOGICOS,HERMANOS_CAT,CARGA_LABORAL,CARGA_HOGAR,CONDICION_DISCAPACIDAD,HABITOS_RIESGO,IMC_CAT
0,1069737604,M,2,Bicicleta,Otro,Recursos propios,CON_CARGAS,Si,Mixto,Propia pagada,Zona urbana,Si,No,2,Si,No,No,Con poca frecuencia,Heterosexual,Comuna Sur Occidental,Media,Media,No,No,No étnico,MEDIO,COMPLETOS,POCOS_1_2,NO_TRABAJA,CON_NINOS_1_2,COGNITIVA,NINGUNO,OBESIDAD
1,1026290752,M,9,Vehículo motorizado,Baja frecuencia,Recursos propios,CON_CARGAS,Si,Mixto,Propia pagada,Zona urbana,Si,No,1,No,No,No,Casi nunca,Heterosexual,Bogota,Media,Media,No,No,No étnico,BAJO,COMPLETOS,VARIOS_3_MAS,NO_TRABAJA,CON_NINOS_1_2,COGNITIVA,BAJO,SOBREPESO
2,1069750774,M,9,A pie,Baja frecuencia,Recursos propios,CON_CARGAS,Si,Diurno,Arrendada,Zona urbana,Si,No,1,Si,No,NaN,Casi nunca,No responde,Comuna Sur Occidental,Media,Media,No,No,No étnico,ALTO,COMPLETOS,VARIOS_3_MAS,NO_TRABAJA,HOGAR_SIN_NINOS,COGNITIVA,NINGUNO,SOBREPESO
3,1069747785,M,5,A pie,Alta frecuencia,Otro / No aplica,SIN_CARGAS,Si,Diurno,Arrendada,Zona urbana,Si,Si,0,No,No,No,Con poca frecuencia,No responde,Comuna Occidental,Superior,Superior,No,No,No étnico,ALTO,COMPLETOS,POCOS_1_2,ALTA_>20,HOGAR_SIN_NINOS,COGNITIVA,BAJO,SOBREPESO
4,1069760977,M,9,A pie,Baja frecuencia,Recursos propios,SIN_CARGAS,Si,Mixto,Arrendada,Zona urbana,Si,No,0,Si,No,Si,Casi nunca,Heterosexual,Comuna Sur Oriental,Básica,Básica,No,No,No étnico,ALTO,BASICOS,VARIOS_3_MAS,ALTA_>20,CON_NINOS_3_MAS,COGNITIVA,BAJO,NORMAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
825,11202693,M,6,Servicio público,Baja frecuencia,Recursos propios,CON_CARGAS,Si,Mixto,Arrendada,Zona urbana,No,Si,1,Si,Sí,No,Frecuentemente,Heterosexual,Comuna Norte,Media,Media,Sí,No,No étnico,ALTO,BASICOS,POCOS_1_2,NO_TRABAJA,CON_NINOS_1_2,COGNITIVA,NINGUNO,SOBREPESO
826,1023970909,M,0,Servicio público,Baja frecuencia,Recursos propios,SIN_CARGAS,No,Diurno,Propia pagandose,Zona urbana,Si,Si,0,Si,Sí,No,Frecuentemente,Heterosexual,Comuna Norte,Media,Media,No,No,No étnico,MEDIO,BASICOS,POCOS_1_2,NO_TRABAJA,HOGAR_SIN_NINOS,COGNITIVA,BAJO,NORMAL
827,1007664640,M,2,Servicio público,Baja frecuencia,Recursos propios,CON_CARGAS,No,Diurno,Arrendada,Zona urbana,Si,No,0,No,No,No,Casi nunca,Heterosexual,Comuna Norte,Superior,Media,No,No,No étnico,MEDIO,COMPLETOS,POCOS_1_2,NO_TRABAJA,SOLO_SIN_NINOS,COGNITIVA,NINGUNO,NORMAL
828,1000693735,F,0,Servicio público,Baja frecuencia,Beca,SIN_CARGAS,No,Mixto,Arrendada,Zona urbana,Si,Si,3,Si,Sí,No,Con poca frecuencia,Heterosexual,Comuna Occidental,Media,Media,No,No,No étnico,BAJO,COMPLETOS,VARIOS_3_MAS,NO_TRABAJA,CON_NINOS_1_2,SIN,BAJO,OBESIDAD
829,1069716513,M,2,Servicio público,Baja frecuencia,Recursos propios,SIN_CARGAS,No,Nocturno,Arrendada,Zona urbana,Si,No,0,No,No,NaN,Frecuentemente,Heterosexual,Comuna Sur Occidental,Superior,Media,No,No,No reportado,BAJO,SIN_RECURSOS,VARIOS_3_MAS,NO_TRABAJA,CON_NINOS_1_2,MULTIPLE,NINGUNO,NORMAL

In [7]:
import os, pandas as pd
print("cwd:", os.getcwd())
print("existe archivo:", os.path.exists("udec_desercion_isc_caracterizacion.csv"))

df_2 = pd.read_csv("udec_desercion_isc_caracterizacion.csv")
print("shape:", df_2.shape)     # (filas, columnas)
print("empty:", df_2.empty)     # False = tiene datos
print(df_2.dtypes.head(10))     # tipos de algunas columnas

cwd: D:\Proyecto_Desercion\notebooks
existe archivo: True
shape: (830, 33)
empty: False
DOCUMENTO                     int64
GENERO                       object
UBICACION_SEMESTRAL           int64
MEDIO_TRANSPORTE             object
FRECUENCIA_TRANSPORTE        object
FUENTES_FINANCIACION         object
PERSONAS_A_CARGO             object
DIFICULTAD_PAGO_MATRICULA    object
TURNO_TRABAJO_ESTUDIO        object
TIPO_VIVIENDA_RESIDENCIA     object
dtype: object

In [8]:
# Mostrar 20 primeras filas SIN truncar columnas
import pandas as pd
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 0)

df_2.head(20).to_string(index=False)

' DOCUMENTO GENERO  UBICACION_SEMESTRAL    MEDIO_TRANSPORTE FRECUENCIA_TRANSPORTE FUENTES_FINANCIACION PERSONAS_A_CARGO DIFICULTAD_PAGO_MATRICULA TURNO_TRABAJO_ESTUDIO TIPO_VIVIENDA_RESIDENCIA ZONA_VIVIENDA_RESIDENCIA VIVE_PADRES_FAMILIAR SISBEN  NUM_HIJOS VIVE_PERSONAS_MAYORES VIVE_PERSONAS_PATOLOGIAS VICTIMA_VIOLENCIA FRECUENCIA_USO_CANALES_ATENCION ORIENTACION_CAT                COMUNA NIV_EDUCATIVO_PADRE_CAT NIV_EDUCATIVO_MADRE_CAT ES_VULNERABLE ES_GRUPO_ETNICO GRUPO_ETNICO_CAT HORAS_FUERA_CASA RECURSOS_TECNOLOGICOS HERMANOS_CAT CARGA_LABORAL     CARGA_HOGAR CONDICION_DISCAPACIDAD HABITOS_RIESGO   IMC_CAT\n1069737604      M                    2           Bicicleta                  Otro     Recursos propios       CON_CARGAS                        Si                 Mixto            Propia pagada              Zona urbana                   Si     No          2                    Si                       No                No             Con poca frecuencia    Heterosexual Comuna Sur Occidental                   Media                   Media            No              No        No étnico            MEDIO             COMPLETOS    POCOS_1_2    NO_TRABAJA   CON_NINOS_1_2              COGNITIVA        NINGUNO  OBESIDAD\n1026290752      M                    9 Vehículo motorizado       Baja frecuencia     Recursos propios       CON_CARGAS                        Si                 Mixto            Propia pagada              Zona urbana                   Si     No          1                    No                       No                No                      Casi nunca    Heterosexual                Bogota                   Media                   Media            No              No        No étnico             BAJO             COMPLETOS VARIOS_3_MAS    NO_TRABAJA   CON_NINOS_1_2              COGNITIVA           BAJO SOBREPESO\n1069750774      M                    9               A pie       Baja frecuencia     Recursos propios       CON_CARGAS                        Si                Diurno                Arrendada              Zona urbana                   Si     No          1                    Si                       No               NaN                      Casi nunca     No responde Comuna Sur Occidental                   Media                   Media            No              No        No étnico             ALTO             COMPLETOS VARIOS_3_MAS    NO_TRABAJA HOGAR_SIN_NINOS              COGNITIVA        NINGUNO SOBREPESO\n1069747785      M                    5               A pie       Alta frecuencia     Otro / No aplica       SIN_CARGAS                        Si                Diurno                Arrendada              Zona urbana                   Si     Si          0                    No                       No                No             Con poca frecuencia     No responde     Comuna Occidental                Superior                Superior            No              No        No étnico             ALTO             COMPLETOS    POCOS_1_2      ALTA_>20 HOGAR_SIN_NINOS              COGNITIVA           BAJO SOBREPESO\n1069760977      M                    9               A pie       Baja frecuencia     Recursos propios       SIN_CARGAS                        Si                 Mixto                Arrendada              Zona urbana                   Si     No          0                    Si                       No                Si                      Casi nunca    Heterosexual   Comuna Sur Oriental                  Básica                  Básica            No              No        No étnico             ALTO               BASICOS VARIOS_3_MAS      ALTA_>20 CON_NINOS_3_MAS              COGNITIVA           BAJO    NORMAL\n1069744582      M                    8    Servicio público       Baja frecuencia     Recursos propios       SIN_CARGAS                        No                Diurno                Arrendada               Zona rural                   Si     No          0                    No                       No                No                      Casi nunca     No responde         Comuna Centro                   Media                  Básica            No              No        No étnico             BAJO             COMPLETOS    POCOS_1_2  PARCIAL_1_20 HOGAR_SIN_NINOS              COGNITIVA        NINGUNO SOBREPESO\n1069755791      M                    3    Servicio público       Baja frecuencia     Recursos propios       SIN_CARGAS                        Si                Diurno            Propia pagada              Zona urbana                   Si     Si          0                    Si                       No                No                  Frecuentemente    Heterosexual Comuna Sur Occidental                   Media                   Media            No              No        No étnico             BAJO             COMPLETOS      NINGUNO    NO_TRABAJA HOGAR_SIN_NINOS              COGNITIVA        NINGUNO SOBREPESO\n1032460863      M                    8           Bicicleta       Baja frecuencia     Recursos propios       SIN_CARGAS                        No                Diurno                Arrendada              Zona urbana                   Si     No          0                    No                       No               NaN                      Casi nunca     No responde                Bogota                   Media                Superior            No              No        No étnico            MEDIO             COMPLETOS    POCOS_1_2  PARCIAL_1_20  SOLO_SIN_NINOS              COGNITIVA        NINGUNO    NORMAL\n1069749942      M                    0    Servicio público       Baja frecuencia     Recursos propios       CON_CARGAS                        No                 Mixto                Arrendada              Zona urbana                   Si     Si          1                    Si                       No                No                      Casi nunca    Heterosexual          Comuna Norte                  Básica                  Básica            No              No        No étnico            MEDIO               BASICOS      NINGUNO      ALTA_>20   CON_NINOS_1_2                    SIN        NINGUNO SOBREPESO\n1015451974      M                    9    Servicio público       Baja frecuencia     Recursos propios       SIN_CARGAS                        Si                Diurno            Propia pagada              Zona urbana                   Si     Si          0                    Si                       No                No                      Casi nunca     No responde         Comuna Centro                  Básica                   Media            No              No        No étnico            MEDIO               BASICOS    POCOS_1_2    NO_TRABAJA HOGAR_SIN_NINOS               MULTIPLE           BAJO  OBESIDAD\n1069758182      M                    9               A pie       Baja frecuencia     Recursos propios       SIN_CARGAS                        No                Diurno                Arrendada              Zona urbana                   No     No          0                    No                       No               NaN                  Frecuentemente     No responde     Comuna Occidental                Superior                Superior            No              No     No reportado            MEDIO             COMPLETOS VARIOS_3_MAS    NO_TRABAJA  SOLO_SIN_NINOS               MULTIPLE           BAJO    NORMAL\n1030622115      M                    9               A pie       Baja frecuencia     Recursos propios       CON_CARGAS                        Si                Diurno                Arrendada              Zona urbana                   Si     Si          1                    Si                       No                No             Con poca frecuencia     No responde          Comuna Norte                   Media                   Media            No              No        No étnico             BAJO               BASICOS    POCOS_1_2    NO_TRABAJA   CON_NINOS_1_2              COGNITIVA        NINGUNO SOBREPESO\n1069762616      M                    9               A pie                  Otro     Recursos propios       CON_CARGAS                        Si                 Mixto            Propia pagada              Zona urbana                   Si     No          0                    Si                       No                No                  Frecuentemente    Heterosexual     Comuna Occidental                Superior                   Media            No              No        No étnico             ALTO             COMPLETOS    POCOS_1_2    NO_TRABAJA   CON_NINOS_1_2              COGNITIVA        NINGUNO BAJO_PESO\n1069762376      M                    9               A pie       Baja frecuencia     Recursos propios       SIN_CARGAS                        Si                Diurno            Propia pagada              Zona urbana                   Si     No          0                    No                       No                No                           Nunca     No responde          Comuna Norte                  Básica                   Media            No              No        No étnico             ALTO             COMPLETOS    POCOS_1_2    NO_TRABAJA HOGAR_SIN_NINOS              COGNITIVA           BAJO    NORMAL\n1069760378      M                    5    Servicio público       Baja frecuencia     Otro / No aplica       SIN_CARGAS                        No                Diurno         Propia pagandose              Zona urbana                   Si     No          0                    No                       No                No                      Casi nunca     No responde          Comuna Norte                   Media                   Media            No              No        No étnico             ALTO             COMPLETOS    POCOS_1_2  PARCIAL_1_20  SOLO_SIN_NINOS              COGNITIVA        NINGUNO SOBREPESO\n1022418555      M                    9    Servicio público       Baja frecuencia     Recursos propios       CON_CARGAS                        Si                Diurno                Arrendada              Zona urbana                   Si     Si          0                    Si                       No                No                      Casi nunca     No responde                Bogota                   Media                   Media            No              No        No étnico             BAJO             COMPLETOS      NINGUNO    NO_TRABAJA  SOLO_SIN_NINOS              COGNITIVA           BAJO    NORMAL\n1069743740      F                    9    Servicio público       Baja frecuencia     Recursos propios       CON_CARGAS                        Si                Diurno                Arrendada               Zona rural                   Si     Si          0                    No                       No                No                  Frecuentemente     No responde   Municipios Aledaños                   Media                   Media            No              No        No étnico             ALTO               BASICOS      NINGUNO    NO_TRABAJA HOGAR_SIN_NINOS              COGNITIVA           BAJO BAJO_PESO\n1069761647      M                    9               A pie       Alta frecuencia     Recursos propios       CON_CARGAS                        Si                Diurno                Arrendada              Zona urbana                   No     Si          0                    No                       No                No                      Casi nunca     No responde         Comuna Centro                   Media                Superior            No              No        No étnico             ALTO               BASICOS VARIOS_3_MAS    NO_TRABAJA   CON_NINOS_1_2              COGNITIVA        NINGUNO SOBREPESO\n1069761810      M                    8 Vehículo motorizado       Baja frecuencia                 Beca       CON_CARGAS                        Si                Diurno                Arrendada               Zona rural                   Si     Si          1                    No                       No               NaN             Con poca frecuencia     No responde   Municipios Aledaños                  Básica                  Básica            No              No        No étnico            MEDIO               BASICOS VARIOS_3_MAS  PARCIAL_1_20 CON_NINOS_3_MAS              COGNITIVA        NINGUNO    NORMAL\n1106900081      F                    9    Servicio público       Baja frecuencia     Recursos propios       SIN_CARGAS                        Si                Diurno                Arrendada              Zona urbana                   Si     Si          0                    No                       No                No             Con poca frecuencia     No responde   Municipios Aledaños                   Media                   Media            No              No        No étnico             BAJO             COMPLETOS VARIOS_3_MAS    NO_TRABAJA HOGAR_SIN_NINOS              COGNITIVA           BAJO SOBREPESO'